### ISSUE TITLE
Not working on iOS 14.1

### ISSUE THREAD

**Issue by g3nsvrv** [rodepanda/SpiceCompanion#5]
Hi guys, I was trying to setup my spice companion using my Phone, but I don't get to make it work, I've configured on the Spice tools the api port 1337, password 1337, open the service on the firewall on my win, and using the same port password and ipv4 from the host computer, and nothing happens. I wanna mention also that my network is really transparent and I use regularly other services with custom ports from devices including my phone.

I've use spiceweb for testing and this works great from the phone.

This is the logs that I get leaving the verbose enabled on spicetools:
```
[2020/10/30 02:01:58] I:api: client connected: 192.168.x.x
[2020/10/30 02:01:58] I:api: new request > id: 0, module: info, function: avs
[2020/10/30 02:01:58] I:api::info: handling request
[2020/10/30 02:01:58] I:api: new request > id: 1, module: info, function: launcher
[2020/10/30 02:01:58] I:api::info: handling request
[2020/10/30 02:01:58] I:api: new request > id: 2, module: capture, function: get_screens
[2020/10/30 02:01:58] I:api: client disconnected: 192.168.x.x
```

So it basically connects but then something happens that got disconnected.

![image](https://user-images.githubusercontent.com/11720535/97706788-ff8f5e80-1a94-11eb-8142-0ecb5f756cfd.png)
![image](https://user-images.githubusercontent.com/11720535/97706742-ee465200-1a94-11eb-8107-34c32801ba4d.png)

Using iOS 14.1, iPhone 11,8 (XR) and latest version of spicecompanion 1.3.0

**Comment by rodepanda** [comment]
What's the datecode of the game Spice is running?

**Comment by g3nsvrv** [comment]
where I can check that? if it uses the system global, mine is dd/MM/yyy

**Comment by rodepanda** [comment]
Could you add me on Discord? My name is rodepanda#1637

**Comment by g3nsvrv** [comment]
it works upgrading to latest spicetools
